Add basic models, infra and tests for users service
b1rr0/bottleShelf pull request #2
Opened 2023-10-25 13:59 UTC by ladaguedencre

Testing: go test ./... -v

2023-10-27 11:46 UTC, Slowpokew commented on users_service/.gitignore
Should we make common gitignore for all services?

2023-10-27 11:47 UTC, Slowpokew commented on users_service/go.mod
поясниш за це

2023-10-27 11:54 UTC, ladaguedencre commented on users_service/.gitignore
I created it in second PR, but included only very basic files not dependant on language e.t.c.

2023-10-27 11:54 UTC, ladaguedencre commented on users_service/.gitignore
For example `*.out` may not be applicable for other services

2023-10-28 10:10 UTC, ladaguedencre commented on users_service/.gitignore
Done

2023-10-28 10:19 UTC, Slowpokew approved these changes

2023-10-28 10:32 UTC, b1rr0 requested changes

2023-10-28 10:32 UTC, b1rr0 commented on users_service/models/user.go
> +	Id       string
https://github.com/google/uuid

2023-10-28 10:37 UTC, ladaguedencre commented on users_service/models/user.go
> +	Id       string
Used

2023-10-28 10:42 UTC, b1rr0 approved these changes

2023-10-28 10:42 UTC, merged